

config-version: 2

name: 'github_source'
version: '1.0.0'

require-dbt-version: [">=0.18.0", "<0.19.0"]

models:
    github_source:
        materialized: table
        tmp:
            materialized: view

vars:
    github_source:
        issue_assignee: "{{ source('github', 'issue_assignee') }}"
        issue_closed_history: "{{ source('github', 'issue_closed_history') }}"
        issue_comment: "{{ source('github', 'issue_comment') }}"
        issue_label: "{{ source('github', 'issue_label') }}"
        issue_merged: "{{ source('github', 'issue_merged') }}"
        issue: "{{ source('github', 'issue') }}"
        pull_request_review: "{{ source('github', 'pull_request_review') }}"
        pull_request: "{{ source('github', 'pull_request') }}"
        repository: "{{ source('github', 'repository') }}"
        requested_reviewer_history: "{{ source('github', 'requested_reviewer_history') }}"
        user: "{{ source('github', 'user') }}"
        issue_assignee_pass_through_columns: []
        issue_closed_history_pass_through_columns: []
        issue_comment_pass_through_columns: []
        issue_label_pass_through_columns: []
        issue_merged_pass_through_columns: []
        issue_pass_through_columns: []
        pull_request_review_pass_through_columns: []
        pull_request_pass_through_columns: []
        repository_pass_through_columns: []
        requested_reviewer_history_pass_through_columns: []
        user_pass_through_columns: []
